---
apiVersion: source.toolkit.fluxcd.io/v2
kind: HelmRepository
metadata:
  name: myhelmrepo
  namespace: default
spec:
  interval: 5m
  url: http://192.168.2.176:8080
  secretRef:
    name: myhelmrepo-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: myhelmrepo-secret
  namespace: default
type: kubernetes.io/basic-auth
stringData:
  username: chartuser
  password: mypass
